"""add images field

Revision ID: 171115fde5a7
Revises: 06b6aa7741b3
Create Date: 2025-11-17 21:32:58.909546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '171115fde5a7'
down_revision = '06b6aa7741b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opinion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('images', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opinion', schema=None) as batch_op:
        batch_op.drop_column('images')

    # ### end Alembic commands ###
